version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
  - source: deploy-scripts/website.service
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
      - location: application_stop.sh
        timeout: 100
  BeforeInstall:
      - location: before-install.sh
        timeout: 100
  ApplicationStart:
      - location: application_start.sh
        timeout: 100